// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scholarstack/AdminDashboard.tsx": () => import("../components/mockups/scholarstack/AdminDashboard.tsx"),
  "./components/mockups/scholarstack/LandingPage.tsx": () => import("../components/mockups/scholarstack/LandingPage.tsx"),
  "./components/mockups/scholarstack/NotesPage.tsx": () => import("../components/mockups/scholarstack/NotesPage.tsx"),
  "./components/mockups/scholarstack/ScholarDashboard.tsx": () => import("../components/mockups/scholarstack/ScholarDashboard.tsx"),
  "./components/mockups/scholarstack/StudentDashboard.tsx": () => import("../components/mockups/scholarstack/StudentDashboard.tsx"),
  "./components/mockups/scholarstack/VideoReels.tsx": () => import("../components/mockups/scholarstack/VideoReels.tsx")
};
